version: '3'
services:
  weqdb1:
    build: ./docker-files/mysql1
  weqdb2:
    build: ./docker-files/mysql2
  weq:
    build: ./docker-files/elixir-phoenix
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - weqdb1
      - weqdb2
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
    command: bash -c "mix phx.server"
  weqtest:
    build: ./docker-files/elixir-phoenix
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - weqdb1
      - weqdb2
    environment:
      - MIX_ENV=test
    command: bash -c "echo 'wait stating database...' && sleep 25 && mix test"
